import { Canvas, useFrame } from "@react-three/fiber";
import { ContactShadows, Float, Lightformer, Environment, RoundedBox } from "@react-three/drei";
import { Suspense, useRef } from "react";
import * as THREE from "three";

const treePositions: [number, number, number][] = [[-4.8,.3,-1.2],[-3.8,.25,-2.5],[4.6,.3,-2],[3.7,.25,1.4],[-1.8,.2,2.4],[5.2,.2,.8]];

function Tree({ position }: { position: [number, number, number] }) {
  return <group position={position} scale={.72}><mesh position-y={.55} castShadow><cylinderGeometry args={[.13,.2,1,10]}/><meshStandardMaterial color="#8a6049" roughness={.9}/></mesh><mesh position-y={1.45} castShadow><coneGeometry args={[.7,1.75,14]}/><meshStandardMaterial color="#3fcb6b" roughness={.82}/></mesh><mesh position-y={1.95} castShadow><coneGeometry args={[.52,1.25,14]}/><meshStandardMaterial color="#28a957" roughness={.82}/></mesh></group>;
}
function House({ position, color = "#fff5d8" }: { position: [number,number,number]; color?: string }) {
  return <group position={position}><RoundedBox args={[1.15,.85,1]} radius={.16} smoothness={3} position-y={.43} castShadow><meshStandardMaterial color={color} roughness={.8}/></RoundedBox><mesh rotation={[0,Math.PI/4,0]} position-y={1.08} castShadow><coneGeometry args={[.9,.8,4]}/><meshStandardMaterial color="#e9664f" roughness={.82}/></mesh><mesh position={[0,.4,.51]}><planeGeometry args={[.3,.48]}/><meshStandardMaterial color="#1e7fe0" emissive="#ffc93c" emissiveIntensity={.25}/></mesh></group>;
}
function Cloud({ position, scale=1 }: { position:[number,number,number]; scale?:number }) { return <Float speed={.7} floatIntensity={.2} rotationIntensity={.05}><group position={position} scale={scale}>{[[-.55,0,0],[0,.18,0],[.55,0,0],[.15,-.1,.12]].map((p,i)=><mesh key={i} position={p as [number,number,number]}><sphereGeometry args={[.56,16,12]}/><meshStandardMaterial color="#fff8e8" roughness={.95}/></mesh>)}</group></Float> }
function Balloon() { const ref=useRef<THREE.Group>(null); useFrame((state)=>{if(ref.current) ref.current.rotation.y=Math.sin(state.clock.elapsedTime*.35)*.18}); return <Float speed={1.1} floatIntensity={.45}><group ref={ref} position={[4.8,4,-2]}><mesh scale={[.72,1,.72]} castShadow><sphereGeometry args={[.75,24,18]}/><meshStandardMaterial color="#f59b23" roughness={.72}/></mesh><mesh scale={[.38,1.02,.76]}><sphereGeometry args={[.75,18,14]}/><meshStandardMaterial color="#ef6d87" roughness={.78}/></mesh><mesh position={[0,-1.05,0]}><boxGeometry args={[.42,.3,.4]}/><meshStandardMaterial color="#9a6a49"/></mesh></group></Float> }
function Train() { const ref=useRef<THREE.Group>(null); useFrame((state,delta)=>{if(!ref.current)return; const t=state.clock.elapsedTime*.22; ref.current.position.set(Math.cos(t)*3.4,.32,Math.sin(t)*2.15); ref.current.rotation.y=-t;}); return <group ref={ref}><RoundedBox args={[1.15,.52,.58]} radius={.14} smoothness={3} castShadow><meshStandardMaterial color="#1e7fe0" roughness={.6}/></RoundedBox><mesh position={[.38,.31,0]}><boxGeometry args={[.38,.3,.5]}/><meshStandardMaterial color="#fff5d8"/></mesh>{[-.35,.35].map((x)=><group key={x}>{[-.31,.31].map(z=><mesh key={z} position={[x,-.3,z]} rotation-x={Math.PI/2}><cylinderGeometry args={[.14,.14,.12,12]}/><meshStandardMaterial color="#354254"/></mesh>)}</group>)}</group> }
function World({ night }: { night:boolean }) { const group=useRef<THREE.Group>(null); useFrame((state)=>{if(group.current){group.current.rotation.y=THREE.MathUtils.lerp(group.current.rotation.y,state.pointer.x*.08,.025);group.current.rotation.x=THREE.MathUtils.lerp(group.current.rotation.x,-state.pointer.y*.025,.025)}}); return <group ref={group} position-y={-1.1}><mesh scale={[7.2,1.35,5]} receiveShadow castShadow><sphereGeometry args={[1,48,24]}/><meshStandardMaterial color="#a8e0a0" roughness={.86}/></mesh><mesh position={[-2.8,.45,-1.4]} scale={[2.5,.8,2]} receiveShadow><sphereGeometry args={[1,32,18]}/><meshStandardMaterial color="#d8efc4" roughness={.9}/></mesh><mesh position={[2.8,.35,-1.5]} scale={[2.7,.75,2]} receiveShadow><sphereGeometry args={[1,32,18]}/><meshStandardMaterial color="#bde9ad" roughness={.9}/></mesh><mesh position={[0,.4,0]} rotation-x={-Math.PI/2}><torusGeometry args={[3.05,.12,10,72,Math.PI*2]}/><meshStandardMaterial color="#6f655d" roughness={.8}/></mesh><mesh position={[1.5,.45,1.4]} scale={[1.25,.12,.8]}><sphereGeometry args={[1,24,12]}/><meshStandardMaterial color="#54bce8" roughness={.45}/></mesh><mesh position={[1.5,.55,.75]} rotation-x={-.45}><boxGeometry args={[.6,.04,.55]}/><meshStandardMaterial color="#dcefff"/></mesh><House position={[-2.2,.25,-.1]}/><House position={[2.3,.2,-.5]} color="#ffe7ef"/><House position={[.25,.2,2]} color="#e8f8dc"/>{treePositions.map((p,i)=><Tree key={i} position={p}/>)}<Train/><Balloon/><Cloud position={[-4,4,-2]} scale={.9}/><Cloud position={[2.1,4.8,-3]} scale={.68}/>{night && Array.from({length:16}).map((_,i)=><mesh key={i} position={[-5+(i%8)*1.4,3.2+Math.floor(i/8)*1.1,-4]}><sphereGeometry args={[.025,6,6]}/><meshBasicMaterial color="#fff4ba"/></mesh>)}</group> }
export function ClayScene({ night }: { night:boolean }) { return <Canvas dpr={[1,1.5]} shadows camera={{position:[0,5.4,9.4],fov:44}} gl={{antialias:true,powerPreference:"high-performance"}}><color attach="background" args={[night ? "#173861" : "#b8d7fb"]}/><fog attach="fog" args={[night ? "#173861" : "#dcebff",12,22]}/><hemisphereLight args={[night?"#6c8fc6":"#dcecff",night?"#243c35":"#80ad6d",night?.8:1.45]}/><directionalLight position={[-4,9,6]} intensity={night?.8:2.2} castShadow shadow-mapSize={[1024,1024]} shadow-camera-far={25}/><Suspense fallback={null}><World night={night}/><Environment><Lightformer intensity={1.4} position={[0,7,2]} scale={[10,10,1]}/><Lightformer intensity={.6} color="#dff1ff" position={[-6,2,-2]} rotation-y={Math.PI/2} scale={[12,2,1]}/></Environment><ContactShadows position={[0,-1.08,0]} opacity={.25} scale={16} blur={2.4} far={5}/></Suspense></Canvas> }
