import { useMemo, useState } from "react";
import { Link } from "@tanstack/react-router";
import { AlertTriangle, ArrowRight, Building2, Check, Clock3, MapPin, Minus, Plus, Route, Search, ShieldAlert, Star } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { faqs, features, layers, personas, problems, scores, steps, type PersonaId } from "@/data/nalar";
import { MapVisual } from "./MapVisual";
import { Wordmark } from "./Wordmark";

const problemIcons = [Building2, ShieldAlert, Clock3];

function SectionHeader({ eyebrow, title, description, light = false }: { eyebrow: string; title: string; description?: string; light?: boolean }) {
  return <header className={`section-heading reveal ${light ? "heading-light" : ""}`}><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{description && <p>{description}</p>}</header>;
}

export function ProblemsSection() {
  return <section className="section-pad section-muted" aria-labelledby="masalah-title"><div className="page-shell"><SectionHeader eyebrow="Masalahnya di sini" title="Keputusan besar sering dibuat dengan informasi yang terbatas." description="Listing menjelaskan bangunan. NalarRuang membantu membaca konteks di sekitarnya."/><h2 id="masalah-title" className="sr-only">Masalah pencarian hunian</h2><div className="problem-grid">{problems.map((item,i)=>{const Icon=problemIcons[i] ?? AlertTriangle;return <article className="problem-card reveal" key={item.title}><span className="problem-index">0{i+1}</span><Icon aria-hidden="true"/><h3>{item.title}</h3></article>})}</div><p className="closing-line reveal">Yang kurang bukan semangat, tapi peta yang mengerti gaya hidupmu.</p></div></section>;
}

export function PersonaSection({selected,onToggle}:{selected:PersonaId[];onToggle:(id:PersonaId)=>void}) {
  return <section id="persona" className="section-pad" aria-labelledby="persona-title"><div className="page-shell"><SectionHeader eyebrow="Kenalan sama 4 persona" title="Prioritas berbeda, cara menilai kawasan pun berbeda." description="Pilih satu atau beberapa persona untuk membentuk penilaian yang relevan dengan keseharianmu."/><h2 id="persona-title" className="sr-only">Empat persona NalarRuang</h2><div className="persona-grid">{personas.map((p)=>{const Icon=p.icon;const active=selected.includes(p.id);return <button type="button" aria-pressed={active} aria-label={`${active?"Batalkan":"Pilih"} persona ${p.name}`} onClick={()=>onToggle(p.id)} className={`persona-card ${p.color} reveal ${active?"is-selected":""}`} key={p.id}><span className="persona-accent"/><span className="persona-top"><span className="persona-icon"><Icon/></span><span className="persona-check">{active?<Check/>:null}</span></span><strong>{p.name}</strong><span className="persona-short">{p.short}</span><span className="persona-description">{p.description}</span><span className="persona-rating-label">Bobot penilaian</span><span className="persona-stars" aria-label="3 dari 3 bintang">{[1,2,3].map(n=><Star key={n}/>)}</span></button>})}</div></div></section>;
}

export function StepsSection() {
  return <section id="cara-kerja" className="section-pad section-muted" aria-labelledby="steps-title"><div className="page-shell"><SectionHeader eyebrow="Cara kerja" title="Tiga langkah, lima menit." description="Dari preferensi hingga perbandingan kawasan dalam satu alur yang ringkas."/><h2 id="steps-title" className="sr-only">Tiga langkah menggunakan NalarRuang</h2><div className="steps-grid">{steps.map((step)=><article className="step-card reveal" key={step.number}><span className="step-number">{step.number}</span><div><h3>{step.title}</h3><p>{step.text}</p></div></article>)}</div></div></section>;
}

export function LayersSection() {
  const [active,setActive]=useState(0);
  return <section id="layer-peta" className="section-pad section-dark" aria-labelledby="layers-title"><div className="page-shell"><SectionHeader eyebrow="Visual Explorer" title="Enam layer untuk membaca kota dengan lebih utuh." description="Pilih perspektif data yang paling relevan, tanpa memenuhi peta dengan informasi yang tidak dibutuhkan." light/><h2 id="layers-title" className="sr-only">Enam layer peta</h2><div className="layers-layout"><div className="layer-tabs" role="tablist" aria-label="Layer peta">{layers.map((layer,i)=>{const Icon=layer.icon;return <button key={layer.title} type="button" role="tab" aria-selected={active===i} onClick={()=>setActive(i)}><Icon/><span><strong>{layer.title}</strong><small>{layer.description}</small></span><ArrowRight/></button>})}</div><div className="layer-preview reveal"><div className="preview-top"><span>Pratinjau data wilayah</span><span>Jabodetabek · 2026</span></div><MapVisual activeLayer={active}/></div></div></div></section>;
}

const featureIcons = [Search, MapPin, Route];
export function FeatureStrip() {
  return <section className="section-pad" aria-labelledby="fit-title"><div className="page-shell"><SectionHeader eyebrow="Seberapa pas?" title="Data yang dapat ditindaklanjuti, bukan sekadar dilihat." description="Tiga perangkat analisis untuk membantu mempersempit pilihan secara sistematis."/><h2 id="fit-title" className="sr-only">Fitur utama NalarRuang</h2><div className="feature-list">{features.map((feature,i)=>{const Icon=featureIcons[i] ?? Search;return <article key={feature.title} className="feature-row reveal"><div className="feature-wireframe"><div className="wireframe-head"><span/><span/></div>{i===0&&<><div className="search-line"><Search/><span>Daerah mudah transit di Bogor Kota</span></div><div className="result-lines"><i/><i/><i/></div></>}{i===1&&<MapVisual compact activeLayer={1}/>} {i===2&&<div className="commute-chart"><span><i style={{width:"72%"}}/>Kendaraan pribadi <b>42 mnt</b></span><span><i style={{width:"48%"}}/>Transportasi publik <b>58 mnt</b></span><div><Route/></div></div>}</div><div className="feature-copy"><span className="feature-number">0{i+1}</span><Icon/><small>{feature.label}</small><h3>{feature.title}</h3><p>{feature.text}</p></div></article>})}</div></div></section>;
}

function Rating({value}:{value:number}) { return <span className="rating" aria-label={`${value} dari 3 bintang`}>{[1,2,3].map(n=><Star key={n} className={n<=value?"filled":""}/>)}</span>; }
export function DemoSection({selected,onToggle}:{selected:PersonaId[];onToggle:(id:PersonaId)=>void}) {
  const [mode,setMode]=useState<"point"|"area">("point"); const modeScores=scores[mode];
  const summary=useMemo(()=>selected.map(id=>{const p=personas.find(x=>x.id===id);const s=modeScores[id];const words=["kurang sesuai","cukup sesuai","sesuai","sangat sesuai"];return `${p?.name}: ${words[s]}.`}),[selected,modeScores]);
  return <section className="section-pad demo-section" aria-labelledby="demo-title"><div className="page-shell"><SectionHeader eyebrow="Coba cepat" title="Lihat bagaimana satu lokasi dinilai." description="Ubah cakupan penilaian dan persona untuk melihat ringkasan yang diperbarui secara langsung."/><h2 id="demo-title" className="sr-only">Demo Point Inspector</h2><div className="dashboard reveal"><div className="dashboard-map"><MapVisual compact activeLayer={3}/></div><div className="inspector"><div className="inspector-top"><span className="data-label">Contoh data</span><div className="segmented" aria-label="Jenis penilaian">{([['point','Titik'],['area','Wilayah']] as const).map(([value,label])=><button type="button" key={value} aria-pressed={mode===value} onClick={()=>setMode(value)}>{label}</button>)}</div></div><div className="location-line"><MapPin/><div><small>{mode==='point'?'TITIK PILIHAN':'WILAYAH PILIHAN'}</small><h3>{mode==='point'?'Taman Kota BSD':'Kecamatan Menteng'}</h3><p>{mode==='point'?'Tangerang Selatan':'Jakarta Pusat'}</p></div></div><div className="score-list">{personas.map(p=><label key={p.id} className={selected.includes(p.id)?"active":""}><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>onToggle(p.id)}/><span className={`score-dot ${p.color}`}/><strong>{p.name}</strong><Rating value={modeScores[p.id]}/></label>)}</div><div className="auto-summary"><small>RINGKASAN OTOMATIS</small>{summary.length?<ul>{summary.map(s=><li key={s}>{s}</li>)}</ul>:<p>Pilih persona untuk melihat ringkasannya.</p>}</div></div></div><p className="demo-note"><AlertTriangle/> Titik dinilai berdasarkan jarak ke fasilitas; wilayah berdasarkan ketersediaan fasilitas.</p></div></section>;
}

export function FaqSection() { return <section id="faq" className="section-pad" aria-labelledby="faq-title"><div className="page-shell faq-shell"><div><span className="eyebrow">FAQ</span><h2 id="faq-title">Pertanyaan yang sering diajukan.</h2><p>Informasi penting tentang sumber data, cakupan, dan cara membaca hasil.</p></div><Accordion type="single" collapsible className="faq-list">{faqs.map(([q,a],i)=><AccordionItem value={`faq-${i}`} key={q}><AccordionTrigger><span>{q}</span><Plus className="faq-plus"/><Minus className="faq-minus"/></AccordionTrigger><AccordionContent>{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>; }
export function CtaSection() { return <section className="cta-wrap"><div className="page-shell cta-inner"><div><span className="eyebrow">Mulai eksplorasi</span><h2>Siap cari hunian yang pas?</h2><p>Mulai dari gaya hidupmu, lalu gunakan data untuk menyaring pilihan.</p></div><Button asChild size="xl"><Link to="/app">Mulai Cari Hunian <ArrowRight/></Link></Button></div></section>; }
export function Footer() { return <footer className="site-footer"><div className="page-shell footer-grid"><div><Wordmark compact/><p>WebGIS untuk membantu masyarakat menemukan kawasan hunian ideal di Jabodetabek.</p></div><nav aria-label="Navigasi footer"><strong>Navigasi</strong><a href="#cara-kerja">Cara Kerja</a><a href="#persona">Persona</a><a href="#layer-peta">Layer Peta</a><a href="#faq">FAQ</a></nav><div className="footer-note"><strong>Catatan data</strong><p>Skor dan rekomendasi bersifat estimasi dari data sekunder publik.</p></div></div><div className="page-shell footer-bottom"><span>© 2026 NalarRuang</span><span>Dibuat di Indonesia</span></div></footer>; }
