import { useMemo, useState } from "react";
import { Link } from "@tanstack/react-router";
import { Check, Star, MapPin, Sparkles, ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { faqs, features, layers, personas, problems, scores, steps, type PersonaId } from "@/data/nalar";
import { Flower, IslandIllustration, PaletteDots, Starburst } from "./Decorations";
import { Wordmark } from "./Wordmark";

export function ProblemsSection(){return <section className="pattern-gingham section-pad" aria-labelledby="masalah-title"><div className="page-shell"><header className="section-heading"><span className="paper-label">REALITA CARI HUNIAN</span><h2 id="masalah-title">Masalahnya di sini</h2><p>Listing bisa bilang banyak hal. Tapi belum tentu menjawab yang paling penting buat keseharianmu.</p></header><div className="three-grid">{problems.map((item,i)=><article className={`sticker-card rotate-${i+1}`} key={item.title}><IslandIllustration type={item.type}/><span className="card-number">0{i+1}</span><h3>{item.title}</h3></article>)}</div><p className="closing-line"><span>Yang kurang bukan semangat, tapi peta yang ngerti gaya hidupmu.</span></p></div><Flower className="deco-flower flower-left"/></section>}

export function PersonaSection({selected,onToggle}:{selected:PersonaId[];onToggle:(id:PersonaId)=>void}){return <section id="persona" className="section-pad pattern-paper" aria-labelledby="persona-title"><div className="page-shell"><header className="section-heading"><span className="paper-label label-pink">PILIH YANG KAMU BANGET</span><h2 id="persona-title">Kenalan sama 4 persona</h2><p>Kamu boleh memilih lebih dari satu. Hidup memang jarang cuma punya satu mode.</p></header><div className="persona-grid">{personas.map((p,i)=>{const Icon=p.icon;const active=selected.includes(p.id);return <button type="button" aria-pressed={active} onClick={()=>onToggle(p.id)} className={`persona-card ${p.color} rotate-${(i%3)+1} ${active?"is-selected":""}`} key={p.id}><span className="persona-check">{active?<Check/>:<span/>}</span><span className="persona-icon"><Icon/></span><span className="persona-kicker">{p.short}</span><strong>{p.name}</strong><span className="persona-description">{p.description}</span><span className="persona-stars" aria-label="Tiga bintang"><Star/><Star/><Star/></span></button>})}</div></div></section>}

export function StepsSection(){return <section id="cara-kerja" className="pattern-grass section-pad" aria-labelledby="steps-title"><div className="page-shell"><header className="section-heading on-grass"><span className="paper-label">GAMPANG, KOK</span><h2 id="steps-title">Tiga langkah, lima menit</h2></header><div className="steps-grid">{steps.map((step,i)=><article className="step-card" key={step.number}><Starburst className={`burst-${i+1}`}>{step.number}</Starburst><div><h3>{step.title}</h3><p>{step.text}</p></div></article>)}</div></div></section>}

export function LayersSection(){const [active,setActive]=useState([0,1,3]);return <section id="layer-peta" className="section-pad pattern-sky" aria-labelledby="layers-title"><div className="page-shell"><header className="section-heading"><span className="paper-label label-green">PETANYA GAK CUMA JALAN</span><h2 id="layers-title">Enam layer peta</h2><p>Nyalakan yang kamu butuhkan, matikan sisanya. Peta tetap ringan dibaca.</p></header><div className="layer-grid">{layers.map((layer,i)=>{const Icon=layer.icon;const on=active.includes(i);return <button key={layer.title} type="button" className={`layer-card tone-${layer.tone} ${on?"is-active":""}`} aria-pressed={on} onClick={()=>setActive(v=>v.includes(i)?v.filter(n=>n!==i):[...v,i])}><span className="layer-toggle"><i/></span><span className="layer-illustration"><Icon/>{layer.year&&<span className="year-slider"><i/>2026</span>}</span><strong>{layer.title}</strong><span>{layer.description}</span></button>})}</div></div></section>}

export function FeatureStrip(){return <section className="section-pad feature-band" aria-labelledby="fit-title"><div className="page-shell"><header className="section-heading"><span className="paper-label label-yellow">DARI CARI SAMPAI YAKIN</span><h2 id="fit-title">Seberapa pas?</h2></header><div className="postcard-grid">{features.map((feature,i)=>{const Icon=feature.icon;return <article key={feature.title} className={`postcard rotate-${i+1}`}><span className="postcard-stamp"><Icon/></span><small>{feature.label}</small><h3>{feature.title}</h3><p>{feature.text}</p><PaletteDots/></article>})}</div></div></section>}

function Rating({value}:{value:number}){return <span className="rating" aria-label={`${value} dari 3 bintang`}>{[1,2,3].map(n=><Star key={n} className={n<=value?"filled":""}/>)}</span>}
export function DemoSection({selected,onToggle}:{selected:PersonaId[];onToggle:(id:PersonaId)=>void}){const [mode,setMode]=useState<"point"|"area">("point");const modeScores=scores[mode];const summary=useMemo(()=>selected.map(id=>{const p=personas.find(x=>x.id===id);const s=modeScores[id];const words=["kurang cocok","cukup cocok","cocok","sangat sempurna"];return `${p?.name}: ${words[s]}.`}),[selected,modeScores]);return <section className="pattern-gingham-green section-pad" aria-labelledby="demo-title"><div className="page-shell demo-shell"><div className="demo-copy"><span className="paper-label label-pink">COBA CEPAT</span><h2 id="demo-title">Klik, nilai, baru yakin.</h2><p>Coba bagaimana Point Inspector merangkum sebuah tempat berdasarkan persona pilihanmu.</p><div className="marker-note">Titik dinilai dari jarak ke fasilitas, wilayah dinilai dari jumlah fasilitas.</div></div><div className="inspector postcard"><div className="inspector-top"><span className="data-label">Contoh data</span><div className="segmented" aria-label="Jenis penilaian">{([["point","Titik"],["area","Wilayah"]] as const).map(([value,label])=><button type="button" key={value} aria-pressed={mode===value} onClick={()=>setMode(value)}>{label}</button>)}</div></div><div className="location-line"><span className="pin-sticker"><MapPin/></span><div><small>{mode==="point"?"TITIK PILIHAN":"WILAYAH PILIHAN"}</small><h3>{mode==="point"?"Taman Kota BSD":"Kecamatan Menteng"}</h3></div></div><div className="score-list">{personas.map(p=><label key={p.id} className={selected.includes(p.id)?"active":""}><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>onToggle(p.id)}/><span className={`score-icon ${p.color}`}><p.icon/></span><strong>{p.name}</strong><Rating value={modeScores[p.id]}/></label>)}</div><div className="auto-summary"><Sparkles/><div><small>RINGKASAN OTOMATIS</small>{summary.length?<ul>{summary.map(s=><li key={s}>{s}</li>)}</ul>:<p>Pilih persona untuk melihat ringkasannya.</p>}</div></div></div></div></section>}

export function FaqSection(){return <section id="faq" className="section-pad pattern-paper" aria-labelledby="faq-title"><div className="page-shell faq-shell"><div><span className="paper-label label-green">BIAR MAKIN JELAS</span><h2 id="faq-title">Yang sering ditanyakan</h2><p>Jawaban singkat sebelum kamu mulai menjelajah.</p></div><Accordion type="single" collapsible className="faq-list">{faqs.map(([q,a],i)=><AccordionItem value={`faq-${i}`} key={q}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent>{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>}
export function CtaSection(){return <section className="pattern-gingham cta-wrap"><div className="page-shell"><div className="cta-card"><Flower className="cta-flower"/><Starburst>AYO!</Starburst><div><h2>Siap cari hunian yang pas?</h2><p>Mulai dari gaya hidupmu, lalu biarkan peta membantu menyaring pilihan.</p></div><Button asChild variant="glossy" size="xl"><Link to="/app">Mulai Cari Hunian <ArrowRight/></Link></Button></div></div></section>}
export function Footer(){return <footer className="pattern-grass site-footer"><div className="page-shell footer-grid"><div><Wordmark compact/><p>Platform SIG untuk membantu kamu menemukan kawasan hunian ideal di Jabodetabek.</p></div><nav aria-label="Navigasi footer"><a href="#cara-kerja">Cara Kerja</a><a href="#persona">Persona</a><a href="#layer-peta">Layer Peta</a><a href="#faq">FAQ</a></nav><div className="footer-note"><p>Skor dan rekomendasi bersifat estimasi dari data sekunder publik.</p><strong>Dibuat di Indonesia</strong></div></div></footer>}
